[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python parser.py /app/Informes_X && playwright install chromium --with-deps && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
